### ISSUE TITLE
Cannot compile programs (clang, Mac OS X)

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-benchmarks#44]
I currently get the following error:
```
/Users/atgeirr/opm-build-debug/opm-benchmarks-build/benchmarks/input/benchmark20_grid.grdecl.gz.hex:31939:57: error: invalid suffix 'x' on integer constant
0x6a,0x35,0x00,0xf2,0x17,0x75,0x77,0xc8,0x89,0x46,0x00,0x,
```
It looks like something went wrong in generating this file, and it was truncated in some manner, the above part is the end of the file as it is generated on my system.

**Comment by bska** [comment]
> Still getting 31939, the sed pattern did not seem to work.

Right.  I keep forgetting that OS X uses the (Free)BSD userland so its `sed` does not recognise `\n` in the replacement string.  Next try
```sh
nl="
"
sed -e "s/,/${nl}/g" file | wc -l
```

**Comment by atgeirr** [comment]
I get "unescaped newline inside substitute pattern". But was not the `tr` command above sufficent?

**Comment by bska** [comment]
> I get "unescaped newline inside substitute pattern"

Yeah, sorry.  You need the double backslash that I added as an update:
```sh
nl="
"
sed -e "s/,/\\${nl}/g" file | wc -l
```

> But was not the `tr` command above sufficient?

It possibly was, I didn't look too closely at its semantics, but I'd like to get `sed` working too just to confirm.

**Comment by atgeirr** [comment]
That works. Result is 542959, maddening enough it is different from the tr result!

**Comment by bska** [comment]
> Result is 542959, maddening enough it is different from the `tr` result!

That number probably includes the existing newline characters of the file.  To account for those, use
```sh
nl="
"
expr $(sed -e "s/,/\\${nl}/g" file | wc -l) - $(wc -l file)
```

**Comment by atgeirr** [comment]
> That number probably includes the existing newline characters of the file

Of course, that is it! So the correct answer is that the trouble happens at position 511020 then.
