### ISSUE TITLE
Problem compiling upscale_relperm_benchmark.cpp

### ISSUE THREAD

**Issue by dlmorenob** [OPM/opm-benchmarks#51]
dear all,

I have manage to compile all opm and I am trying to run the benchmark case, however I get the following error message when it is finishing:
```
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp: In function ‘int main(int, char**)’:
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:402:5: error: ‘ParserPrt’ is not a member of ‘Opm’
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:402:20: error: expected ‘;’ before ‘parser’
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:406:5: error: ‘DeckConstPtr’ is not a member of ‘Opm’
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:406:23: error: expected ‘;’ before ‘deck’
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:413:12: error: ‘deck’ was not declared in this scope
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:419:29: error: ‘deck’ was not declared in this scope
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:423:5: error: ‘DeckRecordConstPtr’ is not a member of ‘Opm’
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:423:29: error: expected ‘;’ before ‘specgridRecord’
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:424:17: error: ‘specgridRecord’ was not declared in this scope
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1696:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1697:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1698:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1699:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1700:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
make[2]: *** [CMakeFiles/upscale_relperm_benchmark.dir/benchmarks/upscale_relperm_benchmark.cpp.o] Error 1
make[1]: *** [CMakeFiles/upscale_relperm_benchmark.dir/all] Error 2
make: *** [all] Error 2
```
It seems to me that it is missing a library, in particular the one called opm::ParserPrt.  Could anyone give me an idea of what it going on?

I have the following system:

SB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:qt4-3.1-amd64:qt4-3.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

and have installed everything as mentioned on the home page.

I appreciate any directions as to how to solve the issue.

David

**Comment by bska** [comment]
> It seems to me that it is missing a library, in particular the one called `Opm::ParserPrt`.

Generally I would agree with you on the missing library were it not for a peculiarity of the diagnostic message.  The diagnostic references `ParserPrt` but [the code in the current master branch](https://github.com/OPM/opm-benchmarks/blob/master/benchmarks/upscale_relperm_benchmark.cpp#L402) references
```C++
Opm::ParserPtr
```
(i.e., with `Ptr` rather than `Prt`).

Did you make any kind of change to the `upscale_relperm_benchmark.cpp` file at all?

The library issue would, at least superficially, appear to be a missing [opm-parser](OPM/opm-parser) module.  Did you compile that module yourself?  If so, how?  Do you build the modules within the source tree, as a subdirectory of the source tree or as a completely separate build tree?  Did you install opm-parser on your system or does it exist "only" as a sibling directory of opm-benchmarks?  What messages did you get during system probing (i.e., when running `configure` or `cmake`) for module opm-benchmarks?

**Comment by atgeirr** [comment]
I have a different (yet unresolved, probably Mac specific) build problem (in #44), so I cannot really say what is wrong here. What I can say is that the program does not explicitly
```
#include <opm/parser/eclipse/Parser/Parser.hpp>
```
but depends on its other includes indirectly including this. If you add this line to upscale_relperm_benchmark, what happens?

The Jenkins auto-build reports success for opm-benchmarks some 13 hours ago, and I am not aware of anything happening after that, with the potential to mess up this, so it is a bit strange!

**Comment by dlmorenob** [comment]
Hello,

Mr. bska:

I basically followed the instructions described on https://github.com/OPM/opm-benchmarks.  That is:
1. Install dependent DUNE core modules and SuiteSparse from Debian Packages
2. Then build the OPM modules from source with a shell script.

Also, I noticed the opm-parser was missing so I added it to the variable that downloads and compiles/installs the code:
...
git clone https://github.com/OPM/dune-cornerpoint.git -b release/2013.10
git clone https://github.com/OPM/opm-benchmarks.git
git clone https://github.com/OPM/opm-parser.git
...
modules='opm-core opm-material dune-cornerpoint opm-porsol opm-upscaling opm-parser opm-benchmarks '
then 

for module in ${modules}; do
  mkdir ${module}/build
  cd ${module}/build
  cmake -DUSE_MPI=ON ../
  nice make -j 4
  cd ../../
done

...yes, there was a mistake for I was testing a way to fix it.  I have just downloaded again and got the same error:

/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:404:5: error: ‘ParserPtr’ is not a member of ‘Opm’

Also... I made sure the libraries where installed on /usr/local/include/opm

david@david-Precision-M2400:/usr/local/include/opm$ ls
core  elasticity  json  material  parser  porsol  upscaling
....

andwhen I run ./configure on the terminal I get:

.....
Found opm-upscaling: /usr/local/include 
-- Generating debug symbols: -ggdb3
-- Looking for strip utility
-- Looking for strip utility - found
-- Writing config file "/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/config.h"...
-- This build defaults to installing in /usr/local
-- Found Doxygen: /usr/bin/doxygen 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks
....
So, it is successful.   

Mr. Atgeirr:
 when I include the aforementioned file I get the following:

/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp: In function ‘int main(int, char**)’:
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:846:88: error: no matching function for call to ‘Opm::SinglePhaseUpscaler::init(Opm::DeckConstPtr&, Opm::UpscalerBase<Opm::SimulatorTraits<Opm::Isotropic, Opm::Explicit> >::BoundaryConditionType&, double, double&, int&, int&, bool&)’
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:846:88: note: candidates are:
/usr/local/include/opm/upscaling/UpscalerBase_impl.hpp:64:17: note: void Opm::UpscalerBase<Traits>::init(const Opm::parameter::ParameterGroup&) [with Traits = Opm::SimulatorTraits<Opm::Isotropic, Opm::Explicit>]
/usr/local/include/opm/upscaling/UpscalerBase_impl.hpp:64:17: note:   candidate expects 1 argument, 7 provided
/usr/local/include/opm/upscaling/UpscalerBase_impl.hpp:131:17: note: void Opm::UpscalerBase<Traits>::init(const Opm::EclipseGridParser&, Opm::UpscalerBase<Traits>::BoundaryConditionType, double, double, double, int, int, bool, int, double, int) [with Traits = Opm::SimulatorTraits<Opm::Isotropic, Opm::Explicit>]
/usr/local/include/opm/upscaling/UpscalerBase_impl.hpp:131:17: note:   no known conversion for argument 1 from ‘Opm::DeckConstPtr {aka std::shared_ptr<const Opm::Deck>}’ to ‘const Opm::EclipseGridParser&’
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1698:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1699:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1700:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1701:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:1702:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
make[2]: *** [CMakeFiles/upscale_relperm_benchmark.dir/benchmarks/upscale_relperm_benchmark.cpp.o] Error 1
make[1]: *** [CMakeFiles/upscale_relperm_benchmark.dir/all] Error 2
make: *** [all] Error 2
....

Is there a place I could see how to configure the Jenkins auto-build?

Thank you for helping.

Regards,
David.

**Comment by atgeirr** [comment]
I see a few issues here:
 - You must not (at this point at least) mix release and up-to-date versions of the modules.
 - Do you have old versions installed, that are found and used? The UpscalerBase_impl.hpp in /usr/local looks like an old version. The class EclipseGridParser that is referred to no longer exists, for example. This must be cleaned up (I recommend deleting /usr/local/include/opm and any opm libs in /usr/local/lib or similar directories) to ensure proper behaviour. There are other ways (setting cmake variables explicitly to point to the new dirs, `make install` of the new code) but this is the simplest I think.

> Is there a place I could see how to configure the Jenkins auto-build?

I cannot give you access to that without granting complete privileges, but if you want to set up automatic build testing with Jenkins, I can send the scripts you are interested in if you like.

**Comment by bska** [comment]
> I basically followed the instructions described on https://github.com/OPM/opm-benchmarks 

Okay, I think I have *some* idea of what's happening now.  Those instructions were written quite some time ago and have, regrettably, not been kept up-to-date.  Effectively, those instructions suggest building the current master version of opm-benchmarks alongside the 2013.10 release versions of the upstream OPM modules.  As @atgeirr says, since the instructions were written there have been just enough change to the opm-benchmark sources that that won't work anymore.

As I see it, you have two options.

1. Use the current master version of opm-benchmarks, but then **also** use the current master of all upstream OPM modules

2. Use the release/2013.10/final version of opm-benchmarks

Depending on your use-case either of these options make sense.  For instance, if you want a stable executable that you use for measuring hardware, then option 2 is the most relevant.  On the other hand, if you want to track the software progress of the OPM project, then option 1 is the one to use.

To implement option 1, remove the `-b release/2013.10` argument to `git clone` for the upstream OPM module, and also include
```
git clone https://github.com/OPM/opm-parser.git
```
in the list of commands.

To implement option 2, add `-b release/2013.10/final` to the `git clone` command for module opm-benchmarks.

Do note, however, that option 2 isn't really tested and may fail for unexpected reasons.  If so, please do not hesitate to ask follow-up questions here.

> I have just downloaded again and got the same error:
> 
```
 /home/david/Downloads/opm-whole/opm_mar_2015/opm-benchmarks/benchmarks/upscale_relperm_benchmark.cpp:404:5: error: ‘ParserPtr’ is not a member of ‘Opm’
```

lf I'm being **really** persnickety, that's not actually the same error as before.  This error at least mentions `ParserPtr` rather than `ParserPrt`.

**Comment by akva2** [comment]
david, possibly not something you want to use in general but for test purposes. can you

1) remove all opm and dune system installs you have on your system
2) clone https://github.com/akva2/opm-meta 
3) configure the meta-system with cmake -DCMAKE_BUILD_TYPE=Release -Dcommon_options=-DUSE_MPI -Dewoms_DISABLED=1 (unless you want ewoms)
4) build the meta system

this clones all gits and builds all modules while keeping everything in the build tree (so nothing is installed on the system). you have to do 1) since i haven't jailed it so system libs will override the in-tree ones.

i just ran it on my machine and everything built fine (gcc (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2)

**Comment by dlmorenob** [comment]
to @akva2 : I have two systems now.  In the new one,  I installed it from scratch to match yours, I followed the instructions given and the opm-meta is working fine now, as well as the benchmark model.  It is really good, thank you very much.  On the previous one (system I was working on, ubuntu 12.04) it does not work even though I tried to clean up the system.  The compiler was not 4.9.2, it was gcc 4.6.  I'll keep trying and let you know.

to @bska.  Thank you very much.  Option 1 did not work since the master, I believe, requires a higher compiler version to that I had at the moment, I will try it on my last version of ubuntu.  Option 2 worked much better though, however I was not able to run the benchmark.  There were some memory erros when running it.  I will try it again next week and come back with some more feedback. Thanks.

to @atgeirr.  Thank you, indeed the mixing of the versions was problematic.  Still, I haven't managed to make it work on my ubuntu 12.04 version.  I will keep trying since I think it is important to understand why it is not working well in previous ubuntu versions.  Also, I appreciate if you could share the scripts since I believe I will be working a lot with the software and automatic build testing would be interesting to see.

Overall, I appreciate very much all your help and if there is anything I could to help the project please let me know.

**Comment by atgeirr** [comment]
> Overall, I appreciate very much all your help and if there is anything I could to help the project please let me know.

Good to know that you found the tips useful. One way to help is to keep doing precisely what you have done: reporting issues, problems, feature requests. Improvements to documentation is certainly welcome. If you know programming (C++ in particular) you can contribute your own code, and we'll most likely include it (but telling us what you want to do on the mailing list first can be a good idea, if only to avoid duplicate work).

**Comment by bska** [comment]
> Option 1 did not work since the master, I believe, requires a higher compiler version to that I had at the moment, I will try it on my last version of ubuntu

We try to make sure that OPM builds with GCC 4.4, at least in C++11 mode.  You mention Ubuntu 12.04 and that's what I use on my laptop to build OPM and I hardly ever experience compiler version problems there (although there are occasionally plenty of **other** problems).  I'm a little disappointed that you weren't able to set up that configuration out of the box.

In the interest of discovery, would you mind running the command
```sh
grep CXX_FLAGS CMakeCache.txt
```
from inside the build directory of module opm-core (i.e., `opm-core/build`).  I **suspect**, but would like to verify, that we somehow fail to add the `-std=c++0x` flag to the compiler command.

> Option 2 worked much better though, however I was not able to run the benchmark. There were some memory errors when running it. I will try it again next week and come back with some more feedback.

Please do.
